spring:
  application:
    name: itq-test-problem
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:dev_db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:pass}
